config/routes.rb
Reporte::Application.routes.draw do
  resources :informes

end

app/models/informe.rb
class Informe < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/informes_controller.rb
class InformesController < ApplicationController
  # GET /informes
  # GET /informes.json
  def index
    @informes = Informe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @informes }
    end
  end

  # GET /informes/1
  # GET /informes/1.json
  def show
    @informe = Informe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @informe }
    end
  end

  # GET /informes/new
  # GET /informes/new.json
  def new
    @informe = Informe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @informe }
    end
  end

  # GET /informes/1/edit
  def edit
    @informe = Informe.find(params[:id])
  end

  # POST /informes
  # POST /informes.json
  def create
    @informe = Informe.new(params[:informe])

    respond_to do |format|
      if @informe.save
        format.html { redirect_to @informe, notice: 'Informe was successfully created.' }
        format.json { render json: @informe, status: :created, location: @informe }
      else
        format.html { render action: "new" }
        format.json { render json: @informe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /informes/1
  # PUT /informes/1.json
  def update
    @informe = Informe.find(params[:id])

    respond_to do |format|
      if @informe.update_attributes(params[:informe])
        format.html { redirect_to @informe, notice: 'Informe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @informe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /informes/1
  # DELETE /informes/1.json
  def destroy
    @informe = Informe.find(params[:id])
    @informe.destroy

    respond_to do |format|
      format.html { redirect_to informes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/informes_helper.rb
module InformesHelper
end

app/views/informes/_form.html.erb
<%= form_for(@informe) do |f| %>
  <% if @informe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@informe.errors.count, "error") %> prohibited this informe from being saved:</h2>

      <ul>
      <% @informe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_lider %><br />
    <%= f.text_field :nombre_lider %>
  </div>
  <div class="field">
    <%= f.label :celula_madre %><br />
    <%= f.text_field :celula_madre %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br />
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :red %><br />
    <%= f.text_field :red %>
  </div>
  <div class="field">
    <%= f.label :hermano %><br />
    <%= f.text_field :hermano %>
  </div>
  <div class="field">
    <%= f.label :amigo %><br />
    <%= f.text_field :amigo %>
  </div>
  <div class="field">
    <%= f.label :acepto %><br />
    <%= f.text_field :acepto %>
  </div>
  <div class="field">
    <%= f.label :reconcilio %><br />
    <%= f.text_field :reconcilio %>
  </div>
  <div class="field">
    <%= f.label :total %><br />
    <%= f.text_field :total %>
  </div>
  <div class="field">
    <%= f.label :asistenigle %><br />
    <%= f.text_field :asistenigle %>
  </div>
  <div class="field">
    <%= f.label :ofrenda %><br />
    <%= f.text_field :ofrenda %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br />
    <%= f.date_select :fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/informes/edit.html.erb
<h1>Editing informe</h1>

<%= render 'form' %>

<%= link_to 'Show', @informe %> |
<%= link_to 'Back', informes_path %>

app/views/informes/index.html.erb
<h1>Listing informes</h1>

<table>
  <tr>
    <th>Nombre lider</th>
    <th>Celula madre</th>
    <th>Telefono</th>
    <th>Red</th>
    <th>Hermano</th>
    <th>Amigo</th>
    <th>Acepto</th>
    <th>Reconcilio</th>
    <th>Total</th>
    <th>Asistenigle</th>
    <th>Ofrenda</th>
    <th>Fecha</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @informes.each do |informe| %>
  <tr>
    <td><%= informe.nombre_lider %></td>
    <td><%= informe.celula_madre %></td>
    <td><%= informe.telefono %></td>
    <td><%= informe.red %></td>
    <td><%= informe.hermano %></td>
    <td><%= informe.amigo %></td>
    <td><%= informe.acepto %></td>
    <td><%= informe.reconcilio %></td>
    <td><%= informe.total %></td>
    <td><%= informe.asistenigle %></td>
    <td><%= informe.ofrenda %></td>
    <td><%= informe.fecha %></td>
    <td><%= link_to 'Show', informe %></td>
    <td><%= link_to 'Edit', edit_informe_path(informe) %></td>
    <td><%= link_to 'Destroy', informe, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Informe', new_informe_path %>

app/views/informes/new.html.erb
<h1>New informe</h1>

<%= render 'form' %>

<%= link_to 'Back', informes_path %>

app/views/informes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre lider:</b>
  <%= @informe.nombre_lider %>
</p>

<p>
  <b>Celula madre:</b>
  <%= @informe.celula_madre %>
</p>

<p>
  <b>Telefono:</b>
  <%= @informe.telefono %>
</p>

<p>
  <b>Red:</b>
  <%= @informe.red %>
</p>

<p>
  <b>Hermano:</b>
  <%= @informe.hermano %>
</p>

<p>
  <b>Amigo:</b>
  <%= @informe.amigo %>
</p>

<p>
  <b>Acepto:</b>
  <%= @informe.acepto %>
</p>

<p>
  <b>Reconcilio:</b>
  <%= @informe.reconcilio %>
</p>

<p>
  <b>Total:</b>
  <%= @informe.total %>
</p>

<p>
  <b>Asistenigle:</b>
  <%= @informe.asistenigle %>
</p>

<p>
  <b>Ofrenda:</b>
  <%= @informe.ofrenda %>
</p>

<p>
  <b>Fecha:</b>
  <%= @informe.fecha %>
</p>


<%= link_to 'Edit', edit_informe_path(@informe) %> |
<%= link_to 'Back', informes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reporte</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>